// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.3
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ExpressionFramework.Core.DomainModel.Builders
{
#nullable enable
    public partial class EmptyExpressionBuilder : ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionBuilder
    {
        public ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionFunctionBuilder? Function
        {
            get;
            set;
        }

        public ExpressionFramework.Abstractions.DomainModel.IExpression Build()
        {
            return new ExpressionFramework.Core.DomainModel.EmptyExpression(Function?.Build());
        }

        public EmptyExpressionBuilder()
        {
        }

        public EmptyExpressionBuilder(ExpressionFramework.Abstractions.DomainModel.IEmptyExpression source)
        {
            Function = source.Function == null ? null : source.Function.ToBuilder();
        }
    }
#nullable restore
}

