// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.8
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ExpressionFramework.Domain.OperatorHandlers
{
#nullable enable
    public class NotEndsWithOperatorHandler : OperatorHandlerBase<NotEndsWithOperator>
    {
        protected override bool Handle(System.Object? leftValue, System.Object? rightValue)
        {
            throw new NotImplementedException();
        }
    }
#nullable restore
}

