// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.3
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ExpressionFramework.Core.DomainModel
{
#nullable enable
    public partial record ConstantExpression : ExpressionFramework.Abstractions.DomainModel.IConstantExpression
    {
        public object? Value
        {
            get;
        }

        public ExpressionFramework.Abstractions.DomainModel.IExpressionFunction? Function
        {
            get;
        }

        public ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionBuilder ToBuilder()
        {
            return new ExpressionFramework.Core.DomainModel.Builders.ConstantExpressionBuilder(this);
        }

        public ConstantExpression(object? value, ExpressionFramework.Abstractions.DomainModel.IExpressionFunction? function)
        {
            this.Value = value;
            this.Function = function;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }
    }
#nullable restore
}

