// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.3
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ExpressionFramework.Abstractions.DomainModel.Extensions
{
#nullable enable
    public static partial class ExpressionBuilderExtensions
    {
        public static T WithFunction<T>(this T instance, ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionFunctionBuilder? function)
            where T : ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionBuilder
        {
            instance.Function = function;
            return instance;
        }
    }
#nullable restore
}

