// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 9.0.3
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace ExpressionFramework.Core.Builders.Abstractions
{
    public partial interface IEvaluatableBuilder
    {
        ExpressionFramework.Core.Abstractions.IEvaluatable Build();
    }
    public partial interface IOperatorBuilder
    {
        ExpressionFramework.Core.Abstractions.IOperator Build();
    }
}
#nullable disable
