// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.3
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ExpressionFramework.Abstractions.DomainModel.Builders
{
#nullable enable
    public partial interface IExpressionFunctionBuilder
    {
        ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionFunctionBuilder? InnerFunction
        {
            get;
            set;
        }

        ExpressionFramework.Abstractions.DomainModel.IExpressionFunction Build();
    }
#nullable restore
}

