// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 8.0.8
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

#nullable enable
namespace ExpressionFramework.Domain.Operators
{
    public partial record EndsWithOperator : ExpressionFramework.Domain.Operator
    {
        public EndsWithOperator() : base()
        {
        }

        public override ExpressionFramework.Domain.Builders.OperatorBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public ExpressionFramework.Domain.Builders.Operators.EndsWithOperatorBuilder ToTypedBuilder()
        {
            return new ExpressionFramework.Domain.Builders.Operators.EndsWithOperatorBuilder(this);
        }
    }
    public partial record EnumerableContainsOperator : ExpressionFramework.Domain.Operator
    {
        public EnumerableContainsOperator() : base()
        {
        }

        public override ExpressionFramework.Domain.Builders.OperatorBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public ExpressionFramework.Domain.Builders.Operators.EnumerableContainsOperatorBuilder ToTypedBuilder()
        {
            return new ExpressionFramework.Domain.Builders.Operators.EnumerableContainsOperatorBuilder(this);
        }
    }
    public partial record EnumerableNotContainsOperator : ExpressionFramework.Domain.Operator
    {
        public EnumerableNotContainsOperator() : base()
        {
        }

        public override ExpressionFramework.Domain.Builders.OperatorBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public ExpressionFramework.Domain.Builders.Operators.EnumerableNotContainsOperatorBuilder ToTypedBuilder()
        {
            return new ExpressionFramework.Domain.Builders.Operators.EnumerableNotContainsOperatorBuilder(this);
        }
    }
    public partial record EqualsOperator : ExpressionFramework.Domain.Operator
    {
        public EqualsOperator() : base()
        {
        }

        public override ExpressionFramework.Domain.Builders.OperatorBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public ExpressionFramework.Domain.Builders.Operators.EqualsOperatorBuilder ToTypedBuilder()
        {
            return new ExpressionFramework.Domain.Builders.Operators.EqualsOperatorBuilder(this);
        }
    }
    public partial record IsGreaterOperator : ExpressionFramework.Domain.Operator
    {
        public IsGreaterOperator() : base()
        {
        }

        public override ExpressionFramework.Domain.Builders.OperatorBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public ExpressionFramework.Domain.Builders.Operators.IsGreaterOperatorBuilder ToTypedBuilder()
        {
            return new ExpressionFramework.Domain.Builders.Operators.IsGreaterOperatorBuilder(this);
        }
    }
    public partial record IsGreaterOrEqualOperator : ExpressionFramework.Domain.Operator
    {
        public IsGreaterOrEqualOperator() : base()
        {
        }

        public override ExpressionFramework.Domain.Builders.OperatorBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public ExpressionFramework.Domain.Builders.Operators.IsGreaterOrEqualOperatorBuilder ToTypedBuilder()
        {
            return new ExpressionFramework.Domain.Builders.Operators.IsGreaterOrEqualOperatorBuilder(this);
        }
    }
    public partial record IsNotNullOperator : ExpressionFramework.Domain.Operator
    {
        public IsNotNullOperator() : base()
        {
        }

        public override ExpressionFramework.Domain.Builders.OperatorBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public ExpressionFramework.Domain.Builders.Operators.IsNotNullOperatorBuilder ToTypedBuilder()
        {
            return new ExpressionFramework.Domain.Builders.Operators.IsNotNullOperatorBuilder(this);
        }
    }
    public partial record IsNotNullOrEmptyOperator : ExpressionFramework.Domain.Operator
    {
        public IsNotNullOrEmptyOperator() : base()
        {
        }

        public override ExpressionFramework.Domain.Builders.OperatorBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public ExpressionFramework.Domain.Builders.Operators.IsNotNullOrEmptyOperatorBuilder ToTypedBuilder()
        {
            return new ExpressionFramework.Domain.Builders.Operators.IsNotNullOrEmptyOperatorBuilder(this);
        }
    }
    public partial record IsNotNullOrWhiteSpaceOperator : ExpressionFramework.Domain.Operator
    {
        public IsNotNullOrWhiteSpaceOperator() : base()
        {
        }

        public override ExpressionFramework.Domain.Builders.OperatorBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public ExpressionFramework.Domain.Builders.Operators.IsNotNullOrWhiteSpaceOperatorBuilder ToTypedBuilder()
        {
            return new ExpressionFramework.Domain.Builders.Operators.IsNotNullOrWhiteSpaceOperatorBuilder(this);
        }
    }
    public partial record IsNullOperator : ExpressionFramework.Domain.Operator
    {
        public IsNullOperator() : base()
        {
        }

        public override ExpressionFramework.Domain.Builders.OperatorBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public ExpressionFramework.Domain.Builders.Operators.IsNullOperatorBuilder ToTypedBuilder()
        {
            return new ExpressionFramework.Domain.Builders.Operators.IsNullOperatorBuilder(this);
        }
    }
    public partial record IsNullOrEmptyOperator : ExpressionFramework.Domain.Operator
    {
        public IsNullOrEmptyOperator() : base()
        {
        }

        public override ExpressionFramework.Domain.Builders.OperatorBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public ExpressionFramework.Domain.Builders.Operators.IsNullOrEmptyOperatorBuilder ToTypedBuilder()
        {
            return new ExpressionFramework.Domain.Builders.Operators.IsNullOrEmptyOperatorBuilder(this);
        }
    }
    public partial record IsNullOrWhiteSpaceOperator : ExpressionFramework.Domain.Operator
    {
        public IsNullOrWhiteSpaceOperator() : base()
        {
        }

        public override ExpressionFramework.Domain.Builders.OperatorBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public ExpressionFramework.Domain.Builders.Operators.IsNullOrWhiteSpaceOperatorBuilder ToTypedBuilder()
        {
            return new ExpressionFramework.Domain.Builders.Operators.IsNullOrWhiteSpaceOperatorBuilder(this);
        }
    }
    public partial record IsSmallerOperator : ExpressionFramework.Domain.Operator
    {
        public IsSmallerOperator() : base()
        {
        }

        public override ExpressionFramework.Domain.Builders.OperatorBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public ExpressionFramework.Domain.Builders.Operators.IsSmallerOperatorBuilder ToTypedBuilder()
        {
            return new ExpressionFramework.Domain.Builders.Operators.IsSmallerOperatorBuilder(this);
        }
    }
    public partial record IsSmallerOrEqualOperator : ExpressionFramework.Domain.Operator
    {
        public IsSmallerOrEqualOperator() : base()
        {
        }

        public override ExpressionFramework.Domain.Builders.OperatorBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public ExpressionFramework.Domain.Builders.Operators.IsSmallerOrEqualOperatorBuilder ToTypedBuilder()
        {
            return new ExpressionFramework.Domain.Builders.Operators.IsSmallerOrEqualOperatorBuilder(this);
        }
    }
    public partial record NotEndsWithOperator : ExpressionFramework.Domain.Operator
    {
        public NotEndsWithOperator() : base()
        {
        }

        public override ExpressionFramework.Domain.Builders.OperatorBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public ExpressionFramework.Domain.Builders.Operators.NotEndsWithOperatorBuilder ToTypedBuilder()
        {
            return new ExpressionFramework.Domain.Builders.Operators.NotEndsWithOperatorBuilder(this);
        }
    }
    public partial record NotEqualsOperator : ExpressionFramework.Domain.Operator
    {
        public NotEqualsOperator() : base()
        {
        }

        public override ExpressionFramework.Domain.Builders.OperatorBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public ExpressionFramework.Domain.Builders.Operators.NotEqualsOperatorBuilder ToTypedBuilder()
        {
            return new ExpressionFramework.Domain.Builders.Operators.NotEqualsOperatorBuilder(this);
        }
    }
    public partial record NotStartsWithOperator : ExpressionFramework.Domain.Operator
    {
        public NotStartsWithOperator() : base()
        {
        }

        public override ExpressionFramework.Domain.Builders.OperatorBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public ExpressionFramework.Domain.Builders.Operators.NotStartsWithOperatorBuilder ToTypedBuilder()
        {
            return new ExpressionFramework.Domain.Builders.Operators.NotStartsWithOperatorBuilder(this);
        }
    }
    public partial record StartsWithOperator : ExpressionFramework.Domain.Operator
    {
        public StartsWithOperator() : base()
        {
        }

        public override ExpressionFramework.Domain.Builders.OperatorBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public ExpressionFramework.Domain.Builders.Operators.StartsWithOperatorBuilder ToTypedBuilder()
        {
            return new ExpressionFramework.Domain.Builders.Operators.StartsWithOperatorBuilder(this);
        }
    }
    public partial record StringContainsOperator : ExpressionFramework.Domain.Operator
    {
        public StringContainsOperator() : base()
        {
        }

        public override ExpressionFramework.Domain.Builders.OperatorBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public ExpressionFramework.Domain.Builders.Operators.StringContainsOperatorBuilder ToTypedBuilder()
        {
            return new ExpressionFramework.Domain.Builders.Operators.StringContainsOperatorBuilder(this);
        }
    }
    public partial record StringNotContainsOperator : ExpressionFramework.Domain.Operator
    {
        public StringNotContainsOperator() : base()
        {
        }

        public override ExpressionFramework.Domain.Builders.OperatorBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public ExpressionFramework.Domain.Builders.Operators.StringNotContainsOperatorBuilder ToTypedBuilder()
        {
            return new ExpressionFramework.Domain.Builders.Operators.StringNotContainsOperatorBuilder(this);
        }
    }
}
#nullable disable
