// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 9.0.3
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace ExpressionFramework.Core.Functions.Evaluatables
{
    public class ComposableEvaluatableFunction : CrossCutting.Utilities.Parsers.Contracts.ITypedFunction<ExpressionFramework.Core.Abstractions.IEvaluatable>
    {
        public CrossCutting.Common.Results.Result<object?> Evaluate(CrossCutting.Utilities.Parsers.FunctionCallContext context)
        {
            return EvaluateTyped(context).Transform<object?>(x => x);
        }

        public CrossCutting.Common.Results.Result<ExpressionFramework.Core.Abstractions.IEvaluatable> EvaluateTyped(CrossCutting.Utilities.Parsers.FunctionCallContext context)
        {
            return new CrossCutting.Common.Results.ResultDictionaryBuilder().Add("InnerEvaluatable", () => context.GetArgumentValueResult<ExpressionFramework.Core.Abstractions.IEvaluatable>(0, "InnerEvaluatable")).Add("Combination", () => context.GetArgumentValueResult<System.Nullable<ExpressionFramework.Core.Domains.Combination>>(1, "Combination")).Add("StartGroup", () => context.GetArgumentValueResult<System.Boolean>(2, "StartGroup")).Add("EndGroup", () => context.GetArgumentValueResult<System.Boolean>(3, "EndGroup")).Build().OnSuccess(results => CrossCutting.Common.Results.Result.Success<ExpressionFramework.Core.Abstractions.IEvaluatable>(new ComposableEvaluatable(results.GetValue<ExpressionFramework.Core.Abstractions.IEvaluatable>("InnerEvaluatable"), results.GetValue<System.Nullable<ExpressionFramework.Core.Domains.Combination>>("Combination"), results.GetValue<System.Boolean>("StartGroup"), results.GetValue<System.Boolean>("EndGroup"))));
        }
    }
    public class ComposedEvaluatableFunction : CrossCutting.Utilities.Parsers.Contracts.ITypedFunction<ExpressionFramework.Core.Abstractions.IEvaluatable>
    {
        public CrossCutting.Common.Results.Result<object?> Evaluate(CrossCutting.Utilities.Parsers.FunctionCallContext context)
        {
            return EvaluateTyped(context).Transform<object?>(x => x);
        }

        public CrossCutting.Common.Results.Result<ExpressionFramework.Core.Abstractions.IEvaluatable> EvaluateTyped(CrossCutting.Utilities.Parsers.FunctionCallContext context)
        {
            return new CrossCutting.Common.Results.ResultDictionaryBuilder().Add("Conditions", () => context.GetArgumentValueResult<System.Collections.Generic.IReadOnlyCollection<ExpressionFramework.Core.Evaluatables.ComposableEvaluatable>>(0, "Conditions")).Build().OnSuccess(results => CrossCutting.Common.Results.Result.Success<ExpressionFramework.Core.Abstractions.IEvaluatable>(new ComposedEvaluatable(results.GetValue<System.Collections.Generic.IReadOnlyCollection<ExpressionFramework.Core.Evaluatables.ComposableEvaluatable>>("Conditions"))));
        }
    }
    public class ConstantEvaluatableFunction : CrossCutting.Utilities.Parsers.Contracts.ITypedFunction<ExpressionFramework.Core.Abstractions.IEvaluatable>
    {
        public CrossCutting.Common.Results.Result<object?> Evaluate(CrossCutting.Utilities.Parsers.FunctionCallContext context)
        {
            return EvaluateTyped(context).Transform<object?>(x => x);
        }

        public CrossCutting.Common.Results.Result<ExpressionFramework.Core.Abstractions.IEvaluatable> EvaluateTyped(CrossCutting.Utilities.Parsers.FunctionCallContext context)
        {
            return new CrossCutting.Common.Results.ResultDictionaryBuilder().Add("Value", () => context.GetArgumentValueResult<System.Boolean>(0, "Value")).Build().OnSuccess(results => CrossCutting.Common.Results.Result.Success<ExpressionFramework.Core.Abstractions.IEvaluatable>(new ConstantEvaluatable(results.GetValue<System.Boolean>("Value"))));
        }
    }
    public class ConstantResultEvaluatableFunction : CrossCutting.Utilities.Parsers.Contracts.ITypedFunction<ExpressionFramework.Core.Abstractions.IEvaluatable>
    {
        public CrossCutting.Common.Results.Result<object?> Evaluate(CrossCutting.Utilities.Parsers.FunctionCallContext context)
        {
            return EvaluateTyped(context).Transform<object?>(x => x);
        }

        public CrossCutting.Common.Results.Result<ExpressionFramework.Core.Abstractions.IEvaluatable> EvaluateTyped(CrossCutting.Utilities.Parsers.FunctionCallContext context)
        {
            return new CrossCutting.Common.Results.ResultDictionaryBuilder().Add("Result", () => context.GetArgumentValueResult<CrossCutting.Common.Results.Result<System.Boolean>>(0, "Result")).Build().OnSuccess(results => CrossCutting.Common.Results.Result.Success<ExpressionFramework.Core.Abstractions.IEvaluatable>(new ConstantResultEvaluatable(results.GetValue<CrossCutting.Common.Results.Result<System.Boolean>>("Result"))));
        }
    }
    public class DelegateEvaluatableFunction : CrossCutting.Utilities.Parsers.Contracts.ITypedFunction<ExpressionFramework.Core.Abstractions.IEvaluatable>
    {
        public CrossCutting.Common.Results.Result<object?> Evaluate(CrossCutting.Utilities.Parsers.FunctionCallContext context)
        {
            return EvaluateTyped(context).Transform<object?>(x => x);
        }

        public CrossCutting.Common.Results.Result<ExpressionFramework.Core.Abstractions.IEvaluatable> EvaluateTyped(CrossCutting.Utilities.Parsers.FunctionCallContext context)
        {
            return new CrossCutting.Common.Results.ResultDictionaryBuilder().Add("Delegate", () => context.GetArgumentValueResult<System.Func<System.Object?,System.Boolean>>(0, "Delegate")).Build().OnSuccess(results => CrossCutting.Common.Results.Result.Success<ExpressionFramework.Core.Abstractions.IEvaluatable>(new DelegateEvaluatable(results.GetValue<System.Func<System.Object?,System.Boolean>>("Delegate"))));
        }
    }
    public class DelegateResultEvaluatableFunction : CrossCutting.Utilities.Parsers.Contracts.ITypedFunction<ExpressionFramework.Core.Abstractions.IEvaluatable>
    {
        public CrossCutting.Common.Results.Result<object?> Evaluate(CrossCutting.Utilities.Parsers.FunctionCallContext context)
        {
            return EvaluateTyped(context).Transform<object?>(x => x);
        }

        public CrossCutting.Common.Results.Result<ExpressionFramework.Core.Abstractions.IEvaluatable> EvaluateTyped(CrossCutting.Utilities.Parsers.FunctionCallContext context)
        {
            return new CrossCutting.Common.Results.ResultDictionaryBuilder().Add("Delegate", () => context.GetArgumentValueResult<System.Func<System.Object?,CrossCutting.Common.Results.Result<System.Boolean>>>(0, "Delegate")).Build().OnSuccess(results => CrossCutting.Common.Results.Result.Success<ExpressionFramework.Core.Abstractions.IEvaluatable>(new DelegateResultEvaluatable(results.GetValue<System.Func<System.Object?,CrossCutting.Common.Results.Result<System.Boolean>>>("Delegate"))));
        }
    }
    public class OperatorEvaluatableFunction : CrossCutting.Utilities.Parsers.Contracts.ITypedFunction<ExpressionFramework.Core.Abstractions.IEvaluatable>
    {
        public CrossCutting.Common.Results.Result<object?> Evaluate(CrossCutting.Utilities.Parsers.FunctionCallContext context)
        {
            return EvaluateTyped(context).Transform<object?>(x => x);
        }

        public CrossCutting.Common.Results.Result<ExpressionFramework.Core.Abstractions.IEvaluatable> EvaluateTyped(CrossCutting.Utilities.Parsers.FunctionCallContext context)
        {
            return new CrossCutting.Common.Results.ResultDictionaryBuilder().Add("LeftValue", () => context.GetArgumentValueResult<System.Object>(0, "LeftValue")).Add("Operator", () => context.GetArgumentValueResult<ExpressionFramework.Core.Abstractions.IOperator>(1, "Operator")).Add("RightValue", () => context.GetArgumentValueResult<System.Object>(2, "RightValue")).Add("StringComparison", () => context.GetArgumentValueResult<System.StringComparison>(3, "StringComparison")).Build().OnSuccess(results => CrossCutting.Common.Results.Result.Success<ExpressionFramework.Core.Abstractions.IEvaluatable>(new OperatorEvaluatable(results.GetValue<System.Object>("LeftValue"), results.GetValue<ExpressionFramework.Core.Abstractions.IOperator>("Operator"), results.GetValue<System.Object>("RightValue"), results.GetValue<System.StringComparison>("StringComparison"))));
        }
    }
}
#nullable disable
