// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 9.0.2
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace ExpressionFramework.Core.Functions.Evaluatables
{
    public class ComposableEvaluatableFunction : CrossCutting.Utilities.Parsers.Contracts.ITypedFunction<ExpressionFramework.Core.Abstractions.IEvaluatable>
    {
        public CrossCutting.Common.Results.Result<object?> Evaluate(CrossCutting.Utilities.Parsers.FunctionCallContext context)
        {
            return EvaluateTyped(context).Transform<object?>(x => x);
        }

        public CrossCutting.Common.Results.Result<ExpressionFramework.Core.Abstractions.IEvaluatable> EvaluateTyped(CrossCutting.Utilities.Parsers.FunctionCallContext context)
        {
            return new CrossCutting.Common.Results.ResultDictionaryBuilder().Add("InnerEvaluatable", () => context.GetArgumentValueResult<IEvaluatable>(0, "InnerEvaluatable")).Add("Combination", () => context.GetArgumentValueResult<Nullable<ExpressionFramework.CodeGeneration.Models.Domains.Combination>>(1, "Combination")).Add("StartGroup", () => context.GetArgumentValueResult<Boolean>(2, "StartGroup")).Add("EndGroup", () => context.GetArgumentValueResult<Boolean>(3, "EndGroup")).Build().OnSuccess(results => CrossCutting.Common.Results.Result.Success<ExpressionFramework.Core.Abstractions.IEvaluatable>(new ComposableEvaluatableBuilder().WithInnerEvaluatable(results.GetValue<IEvaluatable>("InnerEvaluatable").ToBuilder()).WithCombination(results.GetValue<Nullable<ExpressionFramework.CodeGeneration.Models.Domains.Combination>>("Combination")).WithStartGroup(results.GetValue<Boolean>("StartGroup")).WithEndGroup(results.GetValue<Boolean>("EndGroup")).Build()));
        }
    }
    public class ComposedEvaluatableFunction : CrossCutting.Utilities.Parsers.Contracts.ITypedFunction<ExpressionFramework.Core.Abstractions.IEvaluatable>
    {
        public CrossCutting.Common.Results.Result<object?> Evaluate(CrossCutting.Utilities.Parsers.FunctionCallContext context)
        {
            return EvaluateTyped(context).Transform<object?>(x => x);
        }

        public CrossCutting.Common.Results.Result<ExpressionFramework.Core.Abstractions.IEvaluatable> EvaluateTyped(CrossCutting.Utilities.Parsers.FunctionCallContext context)
        {
            return new CrossCutting.Common.Results.ResultDictionaryBuilder().Add("Conditions", () => context.GetArgumentValueResult<IReadOnlyCollection<ExpressionFramework.CodeGeneration.Models.Evaluatables.IComposableEvaluatable>>(0, "Conditions")).Build().OnSuccess(results => CrossCutting.Common.Results.Result.Success<ExpressionFramework.Core.Abstractions.IEvaluatable>(new ComposedEvaluatableBuilder().WithConditions(results.GetValue<IReadOnlyCollection<ExpressionFramework.CodeGeneration.Models.Evaluatables.IComposableEvaluatable>>("Conditions")).Build()));
        }
    }
    public class ConstantEvaluatableFunction : CrossCutting.Utilities.Parsers.Contracts.ITypedFunction<ExpressionFramework.Core.Abstractions.IEvaluatable>
    {
        public CrossCutting.Common.Results.Result<object?> Evaluate(CrossCutting.Utilities.Parsers.FunctionCallContext context)
        {
            return EvaluateTyped(context).Transform<object?>(x => x);
        }

        public CrossCutting.Common.Results.Result<ExpressionFramework.Core.Abstractions.IEvaluatable> EvaluateTyped(CrossCutting.Utilities.Parsers.FunctionCallContext context)
        {
            return new CrossCutting.Common.Results.ResultDictionaryBuilder().Add("Value", () => context.GetArgumentValueResult<Boolean>(0, "Value")).Build().OnSuccess(results => CrossCutting.Common.Results.Result.Success<ExpressionFramework.Core.Abstractions.IEvaluatable>(new ConstantEvaluatableBuilder().WithValue(results.GetValue<Boolean>("Value")).Build()));
        }
    }
    public class ConstantResultEvaluatableFunction : CrossCutting.Utilities.Parsers.Contracts.ITypedFunction<ExpressionFramework.Core.Abstractions.IEvaluatable>
    {
        public CrossCutting.Common.Results.Result<object?> Evaluate(CrossCutting.Utilities.Parsers.FunctionCallContext context)
        {
            return EvaluateTyped(context).Transform<object?>(x => x);
        }

        public CrossCutting.Common.Results.Result<ExpressionFramework.Core.Abstractions.IEvaluatable> EvaluateTyped(CrossCutting.Utilities.Parsers.FunctionCallContext context)
        {
            return new CrossCutting.Common.Results.ResultDictionaryBuilder().Add("Result", () => context.GetArgumentValueResult<Result<System.Boolean>>(0, "Result")).Build().OnSuccess(results => CrossCutting.Common.Results.Result.Success<ExpressionFramework.Core.Abstractions.IEvaluatable>(new ConstantResultEvaluatableBuilder().WithResult(results.GetValue<Result<System.Boolean>>("Result")).Build()));
        }
    }
    public class DelegateEvaluatableFunction : CrossCutting.Utilities.Parsers.Contracts.ITypedFunction<ExpressionFramework.Core.Abstractions.IEvaluatable>
    {
        public CrossCutting.Common.Results.Result<object?> Evaluate(CrossCutting.Utilities.Parsers.FunctionCallContext context)
        {
            return EvaluateTyped(context).Transform<object?>(x => x);
        }

        public CrossCutting.Common.Results.Result<ExpressionFramework.Core.Abstractions.IEvaluatable> EvaluateTyped(CrossCutting.Utilities.Parsers.FunctionCallContext context)
        {
            return new CrossCutting.Common.Results.ResultDictionaryBuilder().Add("Delegate", () => context.GetArgumentValueResult<Func<System.Object?,System.Boolean>>(0, "Delegate")).Build().OnSuccess(results => CrossCutting.Common.Results.Result.Success<ExpressionFramework.Core.Abstractions.IEvaluatable>(new DelegateEvaluatableBuilder().WithDelegate(results.GetValue<Func<System.Object?,System.Boolean>>("Delegate")).Build()));
        }
    }
    public class DelegateResultEvaluatableFunction : CrossCutting.Utilities.Parsers.Contracts.ITypedFunction<ExpressionFramework.Core.Abstractions.IEvaluatable>
    {
        public CrossCutting.Common.Results.Result<object?> Evaluate(CrossCutting.Utilities.Parsers.FunctionCallContext context)
        {
            return EvaluateTyped(context).Transform<object?>(x => x);
        }

        public CrossCutting.Common.Results.Result<ExpressionFramework.Core.Abstractions.IEvaluatable> EvaluateTyped(CrossCutting.Utilities.Parsers.FunctionCallContext context)
        {
            return new CrossCutting.Common.Results.ResultDictionaryBuilder().Add("Delegate", () => context.GetArgumentValueResult<Func<System.Object?,CrossCutting.Common.Results.Result<System.Boolean>>>(0, "Delegate")).Build().OnSuccess(results => CrossCutting.Common.Results.Result.Success<ExpressionFramework.Core.Abstractions.IEvaluatable>(new DelegateResultEvaluatableBuilder().WithDelegate(results.GetValue<Func<System.Object?,CrossCutting.Common.Results.Result<System.Boolean>>>("Delegate")).Build()));
        }
    }
    public class OperatorEvaluatableFunction : CrossCutting.Utilities.Parsers.Contracts.ITypedFunction<ExpressionFramework.Core.Abstractions.IEvaluatable>
    {
        public CrossCutting.Common.Results.Result<object?> Evaluate(CrossCutting.Utilities.Parsers.FunctionCallContext context)
        {
            return EvaluateTyped(context).Transform<object?>(x => x);
        }

        public CrossCutting.Common.Results.Result<ExpressionFramework.Core.Abstractions.IEvaluatable> EvaluateTyped(CrossCutting.Utilities.Parsers.FunctionCallContext context)
        {
            return new CrossCutting.Common.Results.ResultDictionaryBuilder().Add("LeftValue", () => context.GetArgumentValueResult<Object>(0, "LeftValue")).Add("Operator", () => context.GetArgumentValueResult<IOperator>(1, "Operator")).Add("RightValue", () => context.GetArgumentValueResult<Object>(2, "RightValue")).Add("StringComparison", () => context.GetArgumentValueResult<StringComparison>(3, "StringComparison")).Build().OnSuccess(results => CrossCutting.Common.Results.Result.Success<ExpressionFramework.Core.Abstractions.IEvaluatable>(new OperatorEvaluatableBuilder().WithLeftValue(results.GetValue<Object>("LeftValue")).WithOperator(results.GetValue<IOperator>("Operator")).WithRightValue(results.GetValue<Object>("RightValue")).WithStringComparison(results.GetValue<StringComparison>("StringComparison")).Build()));
        }
    }
}
#nullable disable
