// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 9.0.3
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace ExpressionFramework.Core.Abstractions
{
    public partial interface IEvaluatable
    {
        ExpressionFramework.Core.Builders.Abstractions.IEvaluatableBuilder ToBuilder();
    }
    public partial interface IOperator
    {
        ExpressionFramework.Core.Builders.Abstractions.IOperatorBuilder ToBuilder();
    }
}
#nullable disable
